enhance xguardian action: add scan status check with retry logic for improved monitoring

diff --git a/.github/actions/xguardian-actions/action.yml b/.github/actions/xguardian-actions/action.yml
--- a/.github/actions/xguardian-actions/action.yml
+++ b/.github/actions/xguardian-actions/action.yml
@@ -460,6 +460,65 @@ runs:
         check_policies "sca" "${POLICY_SCA}"   # Verifica políticas SCA
         check_policies "dast" "${POLICY_DAST}" # Verifica políticas DAST
 
+    - name: Aguardar finalização do scan
+      shell: bash
+      env:
+        API_TOKEN: ${{ inputs.api_token }}
+        APP_ID: ${{ env.APP_ID }}
+        SCAN_VERSION: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
+      run: |
+        SCAN_STATUS=""
+
+        # Função para verificar o status do scan
+        check_scan_status() {
+          local response=$(curl -s -X GET "https://reporter.xguardianplatform.io/get_scan_pagination/${APP_ID}?page=1&items_per_page=10" \
+            -H 'accept: application/json' \
+            -H "Authorization: Bearer ${API_TOKEN}")
+
+          # Verifica se a resposta é um JSON válido
+          if ! echo "$response" | jq . >/dev/null 2>&1; then
+            echo "Debug: Resposta não é um JSON válido:"
+            echo "$response"
+            return 1
+          fi
+
+          # Busca o scan com o SCAN_VERSION específico
+          SCAN_DATA=$(echo "$response" | jq -r --arg version "${SCAN_VERSION}" '.data[] | select(.scanuuid == $version)')
+
+          if [ -n "$SCAN_DATA" ] && [ "$SCAN_DATA" != "null" ]; then
+            SCAN_STATUS=$(echo "$SCAN_DATA" | jq -r '.scan_status')
+            echo "Scan status: $SCAN_STATUS"
+          else
+            echo "Scan não encontrado na resposta."
+            return 1
+          fi
+        }
+
+        # Loop para verificar o status do scan a cada 2 minutos
+        for i in {1..30}; do
+          echo "Verificando status do scan (tentativa $i de 30)..."
+          if check_scan_status; then
+            if [ "$SCAN_STATUS" == "FINISHED" ]; then
+              echo "Scan finalizado com sucesso."
+              break
+            elif [ "$SCAN_STATUS" == "IN_PROGRESS" ]; then
+              echo "Scan ainda em andamento. Aguardando 2 minutos..."
+              sleep 120
+            else
+              echo "Status inesperado do scan: $SCAN_STATUS"
+              exit 1
+            fi
+          else
+            echo "Erro ao verificar status do scan. Tentando novamente em 2 minutos..."
+            sleep 120
+          fi
+        done
+
+        if [ "$SCAN_STATUS" != "FINISHED" ]; then
+          echo "::error::Scan não foi finalizado após múltiplas tentativas."
+          exit 1
+        fi
+
     - name: Obter o short_sha
       id: vars
       shell: bash
