fix: update SCAN_VERSION and APP_NAME to use inputs instead of repository name in action.yml and run.yml

diff --git a/.github/actions/xguardian-actions/action.yml b/.github/actions/xguardian-actions/action.yml
--- a/.github/actions/xguardian-actions/action.yml
+++ b/.github/actions/xguardian-actions/action.yml
@@ -144,8 +144,8 @@ outputs:
     description: "URL para visualizar os resultados do scan"
     value: ${{ steps.final_outputs.outputs.scan_url }}
   scan_version:
-    description: "Versão do scan (baseada no nome do repositório e SHA do commit)"
-    value: ${{ format('{0}-{1}', github.event.repository.name, steps.vars.outputs.short_sha) }}
+    description: "Versão do scan (baseada no app_name (nome da aplicação) + SHA do commit)"
+    value: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
 
 runs:
   using: "composite"
@@ -274,7 +274,7 @@ runs:
     - name: Verificar se a aplicação existe, caso contrário, cria a aplicação
       shell: bash
       env:
-        APP_NAME: ${{ github.event.repository.name }}
+        APP_NAME: ${{ inputs.app_name }}
         TEAM_ID: ${{ inputs.team_id }}
         LANGUAGES: ${{ inputs.languages }}
         DESCRIPTION: ${{ inputs.description }}
@@ -508,7 +508,7 @@ runs:
         TRANSLATE: ${{ inputs.translate }}
         EXCLUDE: ${{ inputs.exclude }}
         PDF: ${{ inputs.pdf }}
-        SCAN_VERSION: ${{ format('{0}-{1}', github.event.repository.name, steps.vars.outputs.short_sha) }}
+        SCAN_VERSION: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
       run: |
         # Limpa o SCAN_VERSION removendo caracteres especiais e espaços
         CLEAN_SCAN_VERSION=$(echo "${SCAN_VERSION}" | tr -cd '[:alnum:]-_')
@@ -563,7 +563,7 @@ runs:
       env:
         API_TOKEN: ${{ inputs.api_token }}
         APP_ID: ${{ env.APP_ID }}
-        SCAN_VERSION: ${{ format('{0}-{1}', github.event.repository.name, steps.vars.outputs.short_sha) }}
+        SCAN_VERSION: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
         SITE_URL: ${{ inputs.site_url }}
         AUTH_URL: ${{ inputs.auth_url }}
         LOGOUT_URL: ${{ inputs.logout_url }}
@@ -604,6 +604,19 @@ runs:
             -H "Authorization: Bearer ${API_TOKEN}" \
             -H 'Content-Type: application/json' \
             -d "${DATA}")
+        fi
+
+        SCAN_NAME=$(echo "$RESPONSE" | jq -r '.scan_name')
+        APP_NAME=$(echo "$RESPONSE" | jq -r '.app_name')
+        APP_ID=$(echo "$RESPONSE" | jq -r '.app_id')
+
+        if [ -n "$SCAN_NAME" ] && [ -n "$APP_NAME" ] && [ -n "$APP_ID" ]; then
+          echo "Scan Name: $SCAN_NAME"
+          echo "App Name: $APP_NAME"
+          echo "App ID: $APP_ID"
+        else
+          echo "::error::Falha ao obter informações do scan."
+          exit 1
         fi
 
         echo "Resposta do upload DAST:"
@@ -665,7 +678,7 @@ runs:
         SAFE_APP_NAME: ${{ env.SAFE_APP_NAME }}
         APP_NAME: ${{ inputs.app_name }}
         APP_ID: ${{ env.APP_ID }}
-        SCAN_VERSION: ${{ format('{0}-{1}', github.event.repository.name, steps.vars.outputs.short_sha) }}
+        SCAN_VERSION: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
         GET_UPLOAD_URL: ${{ env.GET_UPLOAD_URL }}
       run: |
         echo "Debug: Iniciando upload com SCAN_VERSION: ${SCAN_VERSION}"
@@ -717,7 +730,7 @@ runs:
       env:
         APP_ID: ${{ env.APP_ID }}
         API_TOKEN: ${{ inputs.api_token }}
-        SCAN_VERSION: ${{ format('{0}-{1}', github.event.repository.name, steps.vars.outputs.short_sha) }}
+        SCAN_VERSION: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
         APP_NAME: ${{ inputs.app_name }}
       run: |
         echo "Debug: Buscando scan com versão: ${SCAN_VERSION}"
@@ -862,7 +875,7 @@ runs:
       env:
         API_TOKEN: ${{ inputs.api_token }}
         APP_ID: ${{ env.APP_ID }}
-        SCAN_VERSION: ${{ format('{0}-{1}', github.event.repository.name, steps.vars.outputs.short_sha) }}
+        SCAN_VERSION: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
         SAST_CRITICAL: ${{ env.SAST_CRITICAL }}
         SAST_HIGH: ${{ env.SAST_HIGH }}
         SAST_MEDIUM: ${{ env.SAST_MEDIUM }}
