feat: add logic to retrieve APP_ID if not available in action.yml

diff --git a/.github/actions/xguardian-actions/action.yml b/.github/actions/xguardian-actions/action.yml
--- a/.github/actions/xguardian-actions/action.yml
+++ b/.github/actions/xguardian-actions/action.yml
@@ -542,6 +542,24 @@ runs:
         SCAN_VERSION: ${{ format('{0}-{1}', inputs.app_name, steps.vars.outputs.short_sha) }}
         API_TOKEN: ${{ inputs.api_token }}
       run: |
+        # Verificar se o APP_ID é N/A e buscar o ID correto
+        if [ "${APP_ID}" = "N/A" ]; then
+          echo "APP_ID é N/A, buscando o ID correto..."
+          RESPONSE=$(curl -sS -X GET "${UPLOADER_URL}/get_apps_new?page=1&items_per_page=10" \
+            -H 'accept: application/json' \
+            -H "Authorization: Bearer ${API_TOKEN}")
+
+          APP_ID=$(echo "$RESPONSE" | jq -r --arg NAME "${{ inputs.app_name }}" '.data[] | select(.name == $NAME) | .id')
+
+          if [ -z "$APP_ID" ]; then
+            echo "::error::Não foi possível encontrar o APP_ID para a aplicação ${inputs.app_name}"
+            exit 1
+          fi
+
+          echo "APP_ID encontrado: $APP_ID"
+          echo "APP_ID=$APP_ID" >> $GITHUB_ENV
+        fi
+
         UPLOAD_URL="${UPLOADER_URL}/upload-url"
 
         DATA=$(cat << EOF
