fix: improve vulnerability reporting messages in action.yml for better clarity

diff --git a/.github/actions/xguardian-actions/action.yml b/.github/actions/xguardian-actions/action.yml
--- a/.github/actions/xguardian-actions/action.yml
+++ b/.github/actions/xguardian-actions/action.yml
@@ -1006,27 +1006,28 @@ runs:
               return
             fi
 
-            echo "Políticas definidas para ${scan_type^^} (ID: $policy_id): CRITICAL=$policy_critical, HIGH=$policy_high, MEDIUM=$policy_medium, LOW=$policy_low"
-
             if [ "$critical" -gt 0 ] || [ "$high" -gt 0 ] || [ "$medium" -gt 0 ] || [ "$low" -gt 0 ]; then
+              echo "Políticas definidas para ${scan_type^^} (ID: $policy_id): CRITICAL=$policy_critical, HIGH=$policy_high, MEDIUM=$policy_medium, LOW=$policy_low"
               echo "Vulnerabilidades encontradas para ${scan_type^^}:"
               [ "$critical" -gt 0 ] && echo "CRITICAL=$critical"
               [ "$high" -gt 0 ] && echo "HIGH=$high"
               [ "$medium" -gt 0 ] && echo "MEDIUM=$medium"
               [ "$low" -gt 0 ] && echo "LOW=$low"
-            fi
 
-            if [ "$critical" -gt "$policy_critical" ] || [ "$high" -gt "$policy_high" ] || [ "$medium" -gt "$policy_medium" ] || [ "$low" -gt "$policy_low" ]; then
-              if [ "$pipeaction" == "fail" ]; then
-                echo "::error::Vulnerabilidades ${scan_type^^} excedem as políticas definidas (ID: $policy_id)."
-                exit 1
-              elif [ "$pipeaction" == "warn" ]; then
-                echo "::warning::Vulnerabilidades ${scan_type^^} excedem as políticas definidas (ID: $policy_id)."
+              if [ "$critical" -gt "$policy_critical" ] || [ "$high" -gt "$policy_high" ] || [ "$medium" -gt "$policy_medium" ] || [ "$low" -gt "$policy_low" ]; then
+                if [ "$pipeaction" == "fail" ]; then
+                  echo "::error::Vulnerabilidades ${scan_type^^} excedem as políticas definidas (ID: $policy_id)."
+                  exit 1
+                elif [ "$pipeaction" == "warn" ]; then
+                  echo "::warning::Vulnerabilidades ${scan_type^^} excedem as políticas definidas (ID: $policy_id)."
+                else
+                  echo "::notice::Vulnerabilidades ${scan_type^^} excedem as políticas definidas (ID: $policy_id), mas nenhuma ação foi tomada devido ao pipeaction definido como 'noAction'."
+                fi
               else
-                echo "::notice::Vulnerabilidades ${scan_type^^} excedem as políticas definidas (ID: $policy_id), mas nenhuma ação foi tomada devido ao pipeaction definido como 'noAction'."
+                echo "::notice::Vulnerabilidades ${scan_type^^} estão dentro das políticas definidas (ID: $policy_id)."
               fi
             else
-              echo "::notice::Vulnerabilidades ${scan_type^^} estão dentro das políticas definidas (ID: $policy_id)."
+              echo "::notice::Nenhuma vulnerabilidade encontrada para ${scan_type^^}."
             fi
           }
 
