fix(action): refactor vulnerability checks into a reusable function for improved maintainability

diff --git a/.github/actions/xguardian-actions/action.yml b/.github/actions/xguardian-actions/action.yml
--- a/.github/actions/xguardian-actions/action.yml
+++ b/.github/actions/xguardian-actions/action.yml
@@ -831,38 +831,35 @@ runs:
           DAST_MEDIUM=${DAST_MEDIUM:-0}
           DAST_LOW=${DAST_LOW:-0}
 
-          if [ "$sast_critical" -gt "$SAST_CRITICAL" ] || [ "$sast_high" -gt "$SAST_HIGH" ] || [ "$sast_medium" -gt "$SAST_MEDIUM" ] || [ "$sast_low" -gt "$SAST_LOW" ]; then
-            echo "::error::Vulnerabilidades SAST excedem as políticas definidas."
-            echo "Políticas definidas para SAST: CRITICAL=$SAST_CRITICAL, HIGH=$SAST_HIGH, MEDIUM=$SAST_MEDIUM, LOW=$SAST_LOW"
-            echo "Vulnerabilidades encontradas para SAST: CRITICAL=$sast_critical, HIGH=$sast_high, MEDIUM=$sast_medium, LOW=$sast_low"
-            if [ "$SAST_PIPEACTION" == "fail" ]; then
-              exit 1
-            elif [ "$SAST_PIPEACTION" == "warn" ]; then
-              echo "::warning::Vulnerabilidades SAST excedem as políticas definidas."
-            fi
-          fi
+          check_vulnerabilities() {
+            local scan_type=$1
+            local critical=$2
+            local high=$3
+            local medium=$4
+            local low=$5
+            local policy_critical=$6
+            local policy_high=$7
+            local policy_medium=$8
+            local policy_low=$9
+            local pipeaction=${10}
 
-          if [ "$sca_critical" -gt "$SCA_CRITICAL" ] || [ "$sca_high" -gt "$SCA_HIGH" ] || [ "$sca_medium" -gt "$SCA_MEDIUM" ] || [ "$sca_low" -gt "$SCA_LOW" ]; then
-            echo "::error::Vulnerabilidades SCA excedem as políticas definidas."
-            echo "Políticas definidas para SCA: CRITICAL=$SCA_CRITICAL, HIGH=$SCA_HIGH, MEDIUM=$SCA_MEDIUM, LOW=$SCA_LOW"
-            echo "Vulnerabilidades encontradas para SCA: CRITICAL=$sca_critical, HIGH=$sca_high, MEDIUM=$sca_medium, LOW=$sca_low"
-            if [ "$SCA_PIPEACTION" == "fail" ]; then
-              exit 1
-            elif [ "$SCA_PIPEACTION" == "warn" ]; then
-              echo "::warning::Vulnerabilidades SCA excedem as políticas definidas."
+            if [ "$critical" -gt "$policy_critical" ] || [ "$high" -gt "$policy_high" ] || [ "$medium" -gt "$policy_medium" ] || [ "$low" -gt "$policy_low" ]; then
+              echo "::error::Vulnerabilidades ${scan_type^^} excedem as políticas definidas."
+              echo "Políticas definidas para ${scan_type^^}: CRITICAL=$policy_critical, HIGH=$policy_high, MEDIUM=$policy_medium, LOW=$policy_low"
+              echo "Vulnerabilidades encontradas para ${scan_type^^}: CRITICAL=$critical, HIGH=$high, MEDIUM=$medium, LOW=$low"
+              if [ "$pipeaction" == "fail" ]; then
+                exit 1
+              elif [ "$pipeaction" == "warn" ]; then
+                echo "::warning::Vulnerabilidades ${scan_type^^} excedem as políticas definidas."
+              else
+                echo "::notice::Vulnerabilidades ${scan_type^^} excedem as políticas definidas, mas nenhuma ação foi tomada devido ao pipeaction definido como 'noAction'."
+              fi
             fi
-          fi
+          }
 
-          if [ "$dast_critical" -gt "$DAST_CRITICAL" ] || [ "$dast_high" -gt "$DAST_HIGH" ] || [ "$dast_medium" -gt "$DAST_MEDIUM" ] || [ "$dast_low" -gt "$DAST_LOW" ]; then
-            echo "::error::Vulnerabilidades DAST excedem as políticas definidas."
-            echo "Políticas definidas para DAST: CRITICAL=$DAST_CRITICAL, HIGH=$DAST_HIGH, MEDIUM=$DAST_MEDIUM, LOW=$DAST_LOW"
-            echo "Vulnerabilidades encontradas para DAST: CRITICAL=$dast_critical, HIGH=$dast_high, MEDIUM=$dast_medium, LOW=$dast_low"
-            if [ "$DAST_PIPEACTION" == "fail" ]; then
-              exit 1
-            elif [ "$DAST_PIPEACTION" == "warn" ]; then
-              echo "::warning::Vulnerabilidades DAST excedem as políticas definidas."
-            fi
-          fi
+          check_vulnerabilities "sast" "$sast_critical" "$sast_high" "$sast_medium" "$sast_low" "$SAST_CRITICAL" "$SAST_HIGH" "$SAST_MEDIUM" "$SAST_LOW" "$SAST_PIPEACTION"
+          check_vulnerabilities "sca" "$sca_critical" "$sca_high" "$sca_medium" "$sca_low" "$SCA_CRITICAL" "$SCA_HIGH" "$SCA_MEDIUM" "$SCA_LOW" "$SCA_PIPEACTION"
+          check_vulnerabilities "dast" "$dast_critical" "$dast_high" "$dast_medium" "$dast_low" "$DAST_CRITICAL" "$DAST_HIGH" "$DAST_MEDIUM" "$DAST_LOW" "$DAST_PIPEACTION"
 
           echo "::notice::Todas as vulnerabilidades estão dentro das políticas definidas."
         }
